export const routerPagesNames = {
  login: 'login',
  register: 'register',
  resetPassword: 'reset-password',
  homeAnalytics: 'home/analytics',
  homeIncomeExpenses: 'home/income-expenses',
  homeStatistics: 'home/statistics',
  kitchenClients: 'kitchen/clients',
  kitchenPromoCodes: 'kitchen/promo-codes',
  kitchenSettings: 'kitchen/settings',
  menuIngredients: 'menu/ingredients',
  menuPlans: 'menu/plans',
  menuRecipes: 'menu/recipes',
  ordersFeedback: 'orders/feedback',
  ordersOrders: 'orders/orders',
  settingsCompany: 'settings/company',
  settingsMailbox: 'settings/mailbox',
  settingsProfile: 'settings/profile',
  settingsSubscriptionAndPayment: 'settings/subscription-and-payment',
};
