export const routerPagesNames = {
  home: 'home',
  kitchen: 'kitchen',
  login: 'login',
  menu: 'menu',
  orders: 'orders',
  register: 'register',
  resetPassword: 'reset-password',
  settings: 'settings',
  homeAnalytics: 'home-analytics',
  homeIncomeExpenses: 'home-income-expenses',
  kitchenPromoCodes: 'kitchen-promo-codes',
  kitchenSettings: 'kitchen-settings',
  menuIngredients: 'menu-ingredients',
  menuRecipes: 'menu-recipes',
  ordersFeedback: 'orders-feedback',
  settingsCompany: 'settings-company',
  settingsMailbox: 'settings-mailbox',
  settingsSubscriptionAndPayment: 'settings-subscription-and-payment',
};
